import { ReactNode } from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { cn } from '@/lib'

import './globals.css'
// import 'simplebar-react/dist/simplebar.min.css'
// import 'react-loading-skeleton/dist/skeleton.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode
}>) {
	return (
		<html lang="en" className="light">
			<body className={cn('min-h-screen font-sans antialiased grainy', inter.className)}>{children}</body>
		</html>
	)
}
