import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { PropsWithChildren } from 'react'

import { cn } from '@/lib'
import { Navbar, Providers } from '@/components/shared'

import './globals.css'
// import 'simplebar-react/dist/simplebar.min.css'
// import 'react-loading-skeleton/dist/skeleton.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({ children }: PropsWithChildren) {
	return (
		<html lang="en" className="light">
			<Providers>
				<body className={cn('min-h-screen font-sans antialiased grainy', inter.className)}>
					{/* <Toaster /> */}

					<Navbar />

					{children}
				</body>
			</Providers>
		</html>
	)
}
