import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { PropsWithChildren } from 'react'

import { cn } from '@/lib'
import { Toaster } from '@/components/ui'
import { Navbar } from '@/components/shared/navbar'
import { AuthProvider } from '@/components/shared/auth-provider'

import './globals.css'
import 'simplebar-react/dist/simplebar.min.css'
import 'react-loading-skeleton/dist/skeleton.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const inter = Inter({ subsets: ['latin'] })

export default async function RootLayout({ children }: PropsWithChildren) {
	return (
		<html lang="en" className="light">
			<body className={cn('min-h-screen font-sans antialiased grainy', inter.className)}>
				<AuthProvider>
					<Toaster />

					<Navbar />

					{children}
				</AuthProvider>
			</body>
		</html>
	)
}
